import { Flex, Grid, GridItem } from "@chakra-ui/react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./components/NavBar";
import SideBar from "./components/SideBar";
import "./globals.css";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Grid
            templateAreas={`"nav header"
                  "nav main"
                  "nav footer"`}
            gridTemplateRows={"60px 1fr 30px"}
            gridTemplateColumns={"300px 1fr"}
            minHeight="100vh"
            color="blackAlpha.700"
            fontWeight="bold"
          >
            <GridItem
              pl="3"
              area={"header"}
              borderBottom="1px"
              borderColor="gray.200"
            >
              <NavBar />
            </GridItem>
            <GridItem area={"nav"} borderRight="1px" borderColor="gray.200">
              <SideBar />
            </GridItem>
            <GridItem pl="3" area={"main"}>
              {children}
            </GridItem>
            <GridItem pl="3" area={"footer"}>
              <Flex
                className="w-full h-full"
                justify="center"
                alignItems="center"
              >
                &copy; 2023-2024 HWUM IoT Agriculture | All Rights Reserved
              </Flex>
            </GridItem>
          </Grid>
        </Providers>
      </body>
    </html>
  );
}
